### ISSUE TITLE
Response status code does not indicate success: 406 (NotAcceptable)

### ISSUE THREAD

**Issue by PingPongSet** [Azure-Samples/active-directory-dotnetcore-console-up-v2#6] opened 2019-01-31 21:36 UTC
I got error below by following steps below in this example:

Step 1: Clone or download this repository
Step 2: (Optional) Register the sample with your Azure Active Directory tenant
Choose the Azure AD tenant where you want to create your applications
Register the client app (up-console)
Step 3: Configure the sample to use your Azure AD tenant

Run the app:
```
Enter your username
anyuser@outlook.com
Enter your password (no backspace possible)
*********
Response status code does not indicate success: 406 (NotAcceptable).
Press any key to exit
```

```
Enter your username
anyuser@msn.com
Enter your password (no backspace possible)
*********
Response status code does not indicate success: 406 (NotAcceptable).
Press any key to exit
```

I changed the setting in Supported account types to below, but got the same error
`Accounts in any organizational directory and personal Microsoft accounts (e.g. Skype, Xbox, Outlook.com)`

```
Enter your username
anyuser@outlook.com
Enter your password (no backspace possible)
*********
Response status code does not indicate success: 406 (NotAcceptable).
Press any key to exit
```

Any idea?

anyuser@outlook.com has admin permission

**Comment by jmprieur** [comment] 2019-03-04 16:55
You cannot sign-in a Microsoft Personal Account using username / password. That's by design (for security reasons on the live accounts) as mentioned in https://aka.ms/msal-net-up (see https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Username-Password-Authentication#constraints)

BTW: did you use a tenanted authority? or organizations?

**Comment by jennyf19** [comment] 2019-03-28 20:59
@PingPongSet Any update on the questions from @jmprieur above? thanks.

**Comment by jmprieur** [comment] 2019-06-04 18:49
Closing as there was no answer

**Closed as completed by jmprieur** 2019-06-04 18:49 UTC

**Comment by vaibhavahuja** [comment] 2019-10-13 20:38
> A user account in your Azure AD tenant. This sample will not work with a Microsoft account (formerly Windows Live account). Therefore, if you signed in to the Azure portal with a Microsoft account and have never created a user account in your directory before, you need to do that now.

**Comment by jennyf19** [comment] 2019-10-14 01:09
@vaibhavahuja can you provide some more context for how you got this error?

**Comment by vaibhavahuja** [comment] 2019-10-14 04:16
In the issue described above the user is trying to sign in with his outlook or MSN id. that is not how it would work. the azure ad user is looks something like xxxx@onmicrosoft.com. He got to create a new user in azure ad and then sign in using those credentials. The sample should work after that.

**Comment by jmprieur** [comment] 2019-10-14 06:19
Indeed, username/password (ROPC) is not supported for personal accounts.
See https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-flows-app-scenarios#scenarios-and-supported-authentication-flows, and also https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-acquire-token#constraints-1
